### ISSUE TITLE
Scrollbar styles not working on Mozilla Firefox

### ISSUE THREAD

**Issue by BrNaka** [BrNaka/open-spotify-web#1]
#### Description
The pseudo selector "::-webkit-scrollbar" it's not supported by Mozilla. In Chrome it's ok. Is there an alternative way to style the scrollbar? 

#### Screenshots
![image](https://user-images.githubusercontent.com/31754622/65740325-ad745080-e0be-11e9-9871-64ef0f4cfd39.png)

#### Expected
![image](https://user-images.githubusercontent.com/31754622/65740422-1b207c80-e0bf-11e9-82c7-85f6417d606c.png)

**Comment by lucaspontoexe** [comment]
`::webkit scrollbar` is not cross-platform (see https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar)

There is CSS Scrollbars though. They only work on Firefox (64+). You could use it as a fallback.

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars

**Comment by BrNaka** [comment]
@lucaspontoexe Thanks for the tip, Lucas. I'll try it!
